export const pet_list = [
    {
        id: 1,
        image: '/images/image2.webp',
        code: 'MO231',
        name: 'Pomeranian White',
        gene: 'Male',
        age: '02',
        price: '6.900.000',
    },
    {
        id: 2,
        image: '/images/image1.webp',
        code: '',
        name: '',
        gene: '',
        age: '',
        price: '',
    },    {
        id: 3,
        image: '/images/image3.webp',
        code: '',
        name: '',
        gene: '',
        age: '',
        price: '',
    },    {
        id: 4,
        image: '/images/image4.webp',
        code: '',
        name: '',
        gene: '',
        age: '',
        price: '',
    },    {
        id: 5,
        image: '/images/image5.webp',
        code: '',
        name: '',
        gene: '',
        age: '',
        price: '',
    },    {
        id: 6,
        image: '/images/image6.webp',
        code: '',
        name: '',
        gene: '',
        age: '',
        price: '',
    },    {
        id: 7,
        image: '/images/image7.webp',
        code: '',
        name: '',
        gene: '',
        age: '',
        price: '',
    },    {
        id: 8,
        image: '/images/image8.webp',
        code: '',
        name: '',
        gene: '',
        age: '',
        price: '',
    },
]